name: build
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: cmake -B build .
      - run: cmake --build build --target ci
      - name: "test: success1"
        run: build/src/utf8_to_windows31j_cvt_checker test/inputs/success1.txt
      - name: "test: success1 from stdin"
        run: build/src/utf8_to_windows31j_cvt_checker < test/inputs/success1.txt
      - name: "test: fail1"
        run: |
          EXIT_CODE=0
          build/src/utf8_to_windows31j_cvt_checker test/inputs/fail1.txt || EXIT_CODE=$?
          if [ $EXIT_CODE -eq 1 ]; then
            echo "pass"
            exit 0
          fi
          echo $EXIT_CODE
          exit 1
      - name: "test: fail1 from stdin"
        run: |
          EXIT_CODE=0
          build/src/utf8_to_windows31j_cvt_checker < test/inputs/fail1.txt || EXIT_CODE=$?
          if [ $EXIT_CODE -eq 1 ]; then
            echo "pass"
            exit 0
          fi
          echo $EXIT_CODE
          exit 1
      - name: "check ldd"
        run: ldd build/src/utf8_to_windows31j_cvt_checker
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
        with:
          name: utf8_to_windows31j_cvt_checker
          path: build/src/utf8_to_windows31j_cvt_checker
          retention-days: 2
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/src/utf8_to_windows31j_cvt_checker
  docker_publish:
    runs-on: ubuntu-20.04
    needs: test
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: utf8_to_windows31j_cvt_checker
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: chmod +x utf8_to_windows31j_cvt_checker
      - run: ls -la
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yumetodo/utf8_to_windows31j_cvt_checker:latest
