name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: cmake -B build .
      - run: cmake --build build --target ci
      - name: "check ldd"
        run: ldd build/src/utf8_to_windows31j_cvt_checker
